#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace new_SDLC.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DB_ICT_eSDLC")]
	public partial class db_sdlcDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertTBL_T_APP(TBL_T_APP instance);
    partial void UpdateTBL_T_APP(TBL_T_APP instance);
    partial void DeleteTBL_T_APP(TBL_T_APP instance);
    partial void InsertTBL_M_STEP(TBL_M_STEP instance);
    partial void UpdateTBL_M_STEP(TBL_M_STEP instance);
    partial void DeleteTBL_M_STEP(TBL_M_STEP instance);
    partial void InsertTBL_T_VERSION(TBL_T_VERSION instance);
    partial void UpdateTBL_T_VERSION(TBL_T_VERSION instance);
    partial void DeleteTBL_T_VERSION(TBL_T_VERSION instance);
    partial void InsertTBL_T_ACTIVITY1(TBL_T_ACTIVITY1 instance);
    partial void UpdateTBL_T_ACTIVITY1(TBL_T_ACTIVITY1 instance);
    partial void DeleteTBL_T_ACTIVITY1(TBL_T_ACTIVITY1 instance);
    partial void InsertTBL_M_PIC(TBL_M_PIC instance);
    partial void UpdateTBL_M_PIC(TBL_M_PIC instance);
    partial void DeleteTBL_M_PIC(TBL_M_PIC instance);
    partial void InsertTBL_M_DOC_TYPE(TBL_M_DOC_TYPE instance);
    partial void UpdateTBL_M_DOC_TYPE(TBL_M_DOC_TYPE instance);
    partial void DeleteTBL_M_DOC_TYPE(TBL_M_DOC_TYPE instance);
    partial void InsertTBL_M_PLATFORM(TBL_M_PLATFORM instance);
    partial void UpdateTBL_M_PLATFORM(TBL_M_PLATFORM instance);
    partial void DeleteTBL_M_PLATFORM(TBL_M_PLATFORM instance);
    partial void InsertTBL_M_SERVER(TBL_M_SERVER instance);
    partial void UpdateTBL_M_SERVER(TBL_M_SERVER instance);
    partial void DeleteTBL_M_SERVER(TBL_M_SERVER instance);
    partial void InsertTBL_M_STATUS(TBL_M_STATUS instance);
    partial void UpdateTBL_M_STATUS(TBL_M_STATUS instance);
    partial void DeleteTBL_M_STATUS(TBL_M_STATUS instance);
    partial void InsertTBL_T_DB(TBL_T_DB instance);
    partial void UpdateTBL_T_DB(TBL_T_DB instance);
    partial void DeleteTBL_T_DB(TBL_T_DB instance);
    partial void InsertTBL_T_DOC(TBL_T_DOC instance);
    partial void UpdateTBL_T_DOC(TBL_T_DOC instance);
    partial void DeleteTBL_T_DOC(TBL_T_DOC instance);
    #endregion
		
		public db_sdlcDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public db_sdlcDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public db_sdlcDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public db_sdlcDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<TBL_T_APP> TBL_T_APPs
		{
			get
			{
				return this.GetTable<TBL_T_APP>();
			}
		}
		
		public System.Data.Linq.Table<TBL_M_STEP> TBL_M_STEPs
		{
			get
			{
				return this.GetTable<TBL_M_STEP>();
			}
		}
		
		public System.Data.Linq.Table<TBL_T_VERSION> TBL_T_VERSIONs
		{
			get
			{
				return this.GetTable<TBL_T_VERSION>();
			}
		}
		
		public System.Data.Linq.Table<TBL_T_ACTIVITY1> TBL_T_ACTIVITY1s
		{
			get
			{
				return this.GetTable<TBL_T_ACTIVITY1>();
			}
		}
		
		public System.Data.Linq.Table<TBL_M_PIC> TBL_M_PICs
		{
			get
			{
				return this.GetTable<TBL_M_PIC>();
			}
		}
		
		public System.Data.Linq.Table<TBL_M_DOC_TYPE> TBL_M_DOC_TYPEs
		{
			get
			{
				return this.GetTable<TBL_M_DOC_TYPE>();
			}
		}
		
		public System.Data.Linq.Table<TBL_M_PLATFORM> TBL_M_PLATFORMs
		{
			get
			{
				return this.GetTable<TBL_M_PLATFORM>();
			}
		}
		
		public System.Data.Linq.Table<TBL_M_SERVER> TBL_M_SERVERs
		{
			get
			{
				return this.GetTable<TBL_M_SERVER>();
			}
		}
		
		public System.Data.Linq.Table<TBL_M_STATUS> TBL_M_STATUS
		{
			get
			{
				return this.GetTable<TBL_M_STATUS>();
			}
		}
		
		public System.Data.Linq.Table<TBL_T_DB> TBL_T_DBs
		{
			get
			{
				return this.GetTable<TBL_T_DB>();
			}
		}
		
		public System.Data.Linq.Table<TBL_T_DOC> TBL_T_DOCs
		{
			get
			{
				return this.GetTable<TBL_T_DOC>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.cufn_getAllActivities1", IsComposable=true)]
		public IQueryable<cufn_getAllActivities1Result> cufn_getAllActivities1()
		{
			return this.CreateMethodCallQuery<cufn_getAllActivities1Result>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.cufn_getAllApps", IsComposable=true)]
		public IQueryable<cufn_getAllAppsResult> cufn_getAllApps()
		{
			return this.CreateMethodCallQuery<cufn_getAllAppsResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.cufn_getAllDocs", IsComposable=true)]
		public IQueryable<cufn_getAllDocsResult> cufn_getAllDocs()
		{
			return this.CreateMethodCallQuery<cufn_getAllDocsResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.cufn_getAllVersions", IsComposable=true)]
		public IQueryable<cufn_getAllVersionsResult> cufn_getAllVersions()
		{
			return this.CreateMethodCallQuery<cufn_getAllVersionsResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.cufn_getAllDatabases", IsComposable=true)]
		public IQueryable<cufn_getAllDatabasesResult> cufn_getAllDatabases()
		{
			return this.CreateMethodCallQuery<cufn_getAllDatabasesResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_T_APP")]
	public partial class TBL_T_APP : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _APP_ID;
		
		private string _APP_NAME;
		
		private string _OWNER;
		
		private string _PLATFORM_ID;
		
		private string _SERVER_ID;
		
		private string _STATUS_ID;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnAPP_IDChanging(System.Guid value);
    partial void OnAPP_IDChanged();
    partial void OnAPP_NAMEChanging(string value);
    partial void OnAPP_NAMEChanged();
    partial void OnOWNERChanging(string value);
    partial void OnOWNERChanged();
    partial void OnPLATFORM_IDChanging(string value);
    partial void OnPLATFORM_IDChanged();
    partial void OnSERVER_IDChanging(string value);
    partial void OnSERVER_IDChanged();
    partial void OnSTATUS_IDChanging(string value);
    partial void OnSTATUS_IDChanged();
    #endregion
		
		public TBL_T_APP()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_APP_ID", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid APP_ID
		{
			get
			{
				return this._APP_ID;
			}
			set
			{
				if ((this._APP_ID != value))
				{
					this.OnAPP_IDChanging(value);
					this.SendPropertyChanging();
					this._APP_ID = value;
					this.SendPropertyChanged("APP_ID");
					this.OnAPP_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_APP_NAME", DbType="VarChar(200)")]
		public string APP_NAME
		{
			get
			{
				return this._APP_NAME;
			}
			set
			{
				if ((this._APP_NAME != value))
				{
					this.OnAPP_NAMEChanging(value);
					this.SendPropertyChanging();
					this._APP_NAME = value;
					this.SendPropertyChanged("APP_NAME");
					this.OnAPP_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OWNER", DbType="VarChar(200)")]
		public string OWNER
		{
			get
			{
				return this._OWNER;
			}
			set
			{
				if ((this._OWNER != value))
				{
					this.OnOWNERChanging(value);
					this.SendPropertyChanging();
					this._OWNER = value;
					this.SendPropertyChanged("OWNER");
					this.OnOWNERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PLATFORM_ID", DbType="VarChar(50)")]
		public string PLATFORM_ID
		{
			get
			{
				return this._PLATFORM_ID;
			}
			set
			{
				if ((this._PLATFORM_ID != value))
				{
					this.OnPLATFORM_IDChanging(value);
					this.SendPropertyChanging();
					this._PLATFORM_ID = value;
					this.SendPropertyChanged("PLATFORM_ID");
					this.OnPLATFORM_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SERVER_ID", DbType="VarChar(50)")]
		public string SERVER_ID
		{
			get
			{
				return this._SERVER_ID;
			}
			set
			{
				if ((this._SERVER_ID != value))
				{
					this.OnSERVER_IDChanging(value);
					this.SendPropertyChanging();
					this._SERVER_ID = value;
					this.SendPropertyChanged("SERVER_ID");
					this.OnSERVER_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STATUS_ID", DbType="VarChar(50)")]
		public string STATUS_ID
		{
			get
			{
				return this._STATUS_ID;
			}
			set
			{
				if ((this._STATUS_ID != value))
				{
					this.OnSTATUS_IDChanging(value);
					this.SendPropertyChanging();
					this._STATUS_ID = value;
					this.SendPropertyChanged("STATUS_ID");
					this.OnSTATUS_IDChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_M_STEP")]
	public partial class TBL_M_STEP : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _STEP_ID;
		
		private string _NAME;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSTEP_IDChanging(System.Guid value);
    partial void OnSTEP_IDChanged();
    partial void OnNAMEChanging(string value);
    partial void OnNAMEChanged();
    #endregion
		
		public TBL_M_STEP()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STEP_ID", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid STEP_ID
		{
			get
			{
				return this._STEP_ID;
			}
			set
			{
				if ((this._STEP_ID != value))
				{
					this.OnSTEP_IDChanging(value);
					this.SendPropertyChanging();
					this._STEP_ID = value;
					this.SendPropertyChanged("STEP_ID");
					this.OnSTEP_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAME", DbType="VarChar(200)")]
		public string NAME
		{
			get
			{
				return this._NAME;
			}
			set
			{
				if ((this._NAME != value))
				{
					this.OnNAMEChanging(value);
					this.SendPropertyChanging();
					this._NAME = value;
					this.SendPropertyChanged("NAME");
					this.OnNAMEChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_T_VERSION")]
	public partial class TBL_T_VERSION : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _VERSION_ID;
		
		private System.Nullable<System.DateTime> _DATE;
		
		private string _VERSION;
		
		private string _APP_ID;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnVERSION_IDChanging(System.Guid value);
    partial void OnVERSION_IDChanged();
    partial void OnDATEChanging(System.Nullable<System.DateTime> value);
    partial void OnDATEChanged();
    partial void OnVERSIONChanging(string value);
    partial void OnVERSIONChanged();
    partial void OnAPP_IDChanging(string value);
    partial void OnAPP_IDChanged();
    #endregion
		
		public TBL_T_VERSION()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VERSION_ID", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid VERSION_ID
		{
			get
			{
				return this._VERSION_ID;
			}
			set
			{
				if ((this._VERSION_ID != value))
				{
					this.OnVERSION_IDChanging(value);
					this.SendPropertyChanging();
					this._VERSION_ID = value;
					this.SendPropertyChanged("VERSION_ID");
					this.OnVERSION_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DATE", DbType="Date")]
		public System.Nullable<System.DateTime> DATE
		{
			get
			{
				return this._DATE;
			}
			set
			{
				if ((this._DATE != value))
				{
					this.OnDATEChanging(value);
					this.SendPropertyChanging();
					this._DATE = value;
					this.SendPropertyChanged("DATE");
					this.OnDATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VERSION", DbType="VarChar(50)")]
		public string VERSION
		{
			get
			{
				return this._VERSION;
			}
			set
			{
				if ((this._VERSION != value))
				{
					this.OnVERSIONChanging(value);
					this.SendPropertyChanging();
					this._VERSION = value;
					this.SendPropertyChanged("VERSION");
					this.OnVERSIONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_APP_ID", DbType="VarChar(50)")]
		public string APP_ID
		{
			get
			{
				return this._APP_ID;
			}
			set
			{
				if ((this._APP_ID != value))
				{
					this.OnAPP_IDChanging(value);
					this.SendPropertyChanging();
					this._APP_ID = value;
					this.SendPropertyChanged("APP_ID");
					this.OnAPP_IDChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_T_ACTIVITY1")]
	public partial class TBL_T_ACTIVITY1 : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _ACTIVITY_ID;
		
		private System.Nullable<System.DateTime> _START_DATETIME;
		
		private System.Nullable<System.DateTime> _END_DATETIME;
		
		private string _ACTIVITY_DETAIL;
		
		private string _REMARKS;
		
		private string _APP_ID;
		
		private string _VERSION_ID;
		
		private string _PIC_ID;
		
		private string _STEP_ID;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnACTIVITY_IDChanging(System.Guid value);
    partial void OnACTIVITY_IDChanged();
    partial void OnSTART_DATETIMEChanging(System.Nullable<System.DateTime> value);
    partial void OnSTART_DATETIMEChanged();
    partial void OnEND_DATETIMEChanging(System.Nullable<System.DateTime> value);
    partial void OnEND_DATETIMEChanged();
    partial void OnACTIVITY_DETAILChanging(string value);
    partial void OnACTIVITY_DETAILChanged();
    partial void OnREMARKSChanging(string value);
    partial void OnREMARKSChanged();
    partial void OnAPP_IDChanging(string value);
    partial void OnAPP_IDChanged();
    partial void OnVERSION_IDChanging(string value);
    partial void OnVERSION_IDChanged();
    partial void OnPIC_IDChanging(string value);
    partial void OnPIC_IDChanged();
    partial void OnSTEP_IDChanging(string value);
    partial void OnSTEP_IDChanged();
    #endregion
		
		public TBL_T_ACTIVITY1()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ACTIVITY_ID", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid ACTIVITY_ID
		{
			get
			{
				return this._ACTIVITY_ID;
			}
			set
			{
				if ((this._ACTIVITY_ID != value))
				{
					this.OnACTIVITY_IDChanging(value);
					this.SendPropertyChanging();
					this._ACTIVITY_ID = value;
					this.SendPropertyChanged("ACTIVITY_ID");
					this.OnACTIVITY_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_START_DATETIME", DbType="DateTime")]
		public System.Nullable<System.DateTime> START_DATETIME
		{
			get
			{
				return this._START_DATETIME;
			}
			set
			{
				if ((this._START_DATETIME != value))
				{
					this.OnSTART_DATETIMEChanging(value);
					this.SendPropertyChanging();
					this._START_DATETIME = value;
					this.SendPropertyChanged("START_DATETIME");
					this.OnSTART_DATETIMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_END_DATETIME", DbType="DateTime")]
		public System.Nullable<System.DateTime> END_DATETIME
		{
			get
			{
				return this._END_DATETIME;
			}
			set
			{
				if ((this._END_DATETIME != value))
				{
					this.OnEND_DATETIMEChanging(value);
					this.SendPropertyChanging();
					this._END_DATETIME = value;
					this.SendPropertyChanged("END_DATETIME");
					this.OnEND_DATETIMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ACTIVITY_DETAIL", DbType="VarChar(MAX)")]
		public string ACTIVITY_DETAIL
		{
			get
			{
				return this._ACTIVITY_DETAIL;
			}
			set
			{
				if ((this._ACTIVITY_DETAIL != value))
				{
					this.OnACTIVITY_DETAILChanging(value);
					this.SendPropertyChanging();
					this._ACTIVITY_DETAIL = value;
					this.SendPropertyChanged("ACTIVITY_DETAIL");
					this.OnACTIVITY_DETAILChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_REMARKS", DbType="VarChar(MAX)")]
		public string REMARKS
		{
			get
			{
				return this._REMARKS;
			}
			set
			{
				if ((this._REMARKS != value))
				{
					this.OnREMARKSChanging(value);
					this.SendPropertyChanging();
					this._REMARKS = value;
					this.SendPropertyChanged("REMARKS");
					this.OnREMARKSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_APP_ID", DbType="VarChar(50)")]
		public string APP_ID
		{
			get
			{
				return this._APP_ID;
			}
			set
			{
				if ((this._APP_ID != value))
				{
					this.OnAPP_IDChanging(value);
					this.SendPropertyChanging();
					this._APP_ID = value;
					this.SendPropertyChanged("APP_ID");
					this.OnAPP_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VERSION_ID", DbType="VarChar(50)")]
		public string VERSION_ID
		{
			get
			{
				return this._VERSION_ID;
			}
			set
			{
				if ((this._VERSION_ID != value))
				{
					this.OnVERSION_IDChanging(value);
					this.SendPropertyChanging();
					this._VERSION_ID = value;
					this.SendPropertyChanged("VERSION_ID");
					this.OnVERSION_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PIC_ID", DbType="VarChar(50)")]
		public string PIC_ID
		{
			get
			{
				return this._PIC_ID;
			}
			set
			{
				if ((this._PIC_ID != value))
				{
					this.OnPIC_IDChanging(value);
					this.SendPropertyChanging();
					this._PIC_ID = value;
					this.SendPropertyChanged("PIC_ID");
					this.OnPIC_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STEP_ID", DbType="VarChar(50)")]
		public string STEP_ID
		{
			get
			{
				return this._STEP_ID;
			}
			set
			{
				if ((this._STEP_ID != value))
				{
					this.OnSTEP_IDChanging(value);
					this.SendPropertyChanging();
					this._STEP_ID = value;
					this.SendPropertyChanged("STEP_ID");
					this.OnSTEP_IDChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_M_PIC")]
	public partial class TBL_M_PIC : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _PIC_ID;
		
		private string _NAME;
		
		private string _PIC_DEV;
		
		private string _PIC_OPR;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPIC_IDChanging(System.Guid value);
    partial void OnPIC_IDChanged();
    partial void OnNAMEChanging(string value);
    partial void OnNAMEChanged();
    partial void OnPIC_DEVChanging(string value);
    partial void OnPIC_DEVChanged();
    partial void OnPIC_OPRChanging(string value);
    partial void OnPIC_OPRChanged();
    #endregion
		
		public TBL_M_PIC()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PIC_ID", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid PIC_ID
		{
			get
			{
				return this._PIC_ID;
			}
			set
			{
				if ((this._PIC_ID != value))
				{
					this.OnPIC_IDChanging(value);
					this.SendPropertyChanging();
					this._PIC_ID = value;
					this.SendPropertyChanged("PIC_ID");
					this.OnPIC_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAME", DbType="VarChar(200)")]
		public string NAME
		{
			get
			{
				return this._NAME;
			}
			set
			{
				if ((this._NAME != value))
				{
					this.OnNAMEChanging(value);
					this.SendPropertyChanging();
					this._NAME = value;
					this.SendPropertyChanged("NAME");
					this.OnNAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PIC_DEV", DbType="VarChar(200)")]
		public string PIC_DEV
		{
			get
			{
				return this._PIC_DEV;
			}
			set
			{
				if ((this._PIC_DEV != value))
				{
					this.OnPIC_DEVChanging(value);
					this.SendPropertyChanging();
					this._PIC_DEV = value;
					this.SendPropertyChanged("PIC_DEV");
					this.OnPIC_DEVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PIC_OPR", DbType="VarChar(200)")]
		public string PIC_OPR
		{
			get
			{
				return this._PIC_OPR;
			}
			set
			{
				if ((this._PIC_OPR != value))
				{
					this.OnPIC_OPRChanging(value);
					this.SendPropertyChanging();
					this._PIC_OPR = value;
					this.SendPropertyChanged("PIC_OPR");
					this.OnPIC_OPRChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_M_DOC_TYPE")]
	public partial class TBL_M_DOC_TYPE : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _DOC_TYPE_ID;
		
		private string _TYPE;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnDOC_TYPE_IDChanging(System.Guid value);
    partial void OnDOC_TYPE_IDChanged();
    partial void OnTYPEChanging(string value);
    partial void OnTYPEChanged();
    #endregion
		
		public TBL_M_DOC_TYPE()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOC_TYPE_ID", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid DOC_TYPE_ID
		{
			get
			{
				return this._DOC_TYPE_ID;
			}
			set
			{
				if ((this._DOC_TYPE_ID != value))
				{
					this.OnDOC_TYPE_IDChanging(value);
					this.SendPropertyChanging();
					this._DOC_TYPE_ID = value;
					this.SendPropertyChanged("DOC_TYPE_ID");
					this.OnDOC_TYPE_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TYPE", DbType="VarChar(50)")]
		public string TYPE
		{
			get
			{
				return this._TYPE;
			}
			set
			{
				if ((this._TYPE != value))
				{
					this.OnTYPEChanging(value);
					this.SendPropertyChanging();
					this._TYPE = value;
					this.SendPropertyChanged("TYPE");
					this.OnTYPEChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_M_PLATFORM")]
	public partial class TBL_M_PLATFORM : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _PLATFORM_ID;
		
		private string _NAME;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPLATFORM_IDChanging(System.Guid value);
    partial void OnPLATFORM_IDChanged();
    partial void OnNAMEChanging(string value);
    partial void OnNAMEChanged();
    #endregion
		
		public TBL_M_PLATFORM()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PLATFORM_ID", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid PLATFORM_ID
		{
			get
			{
				return this._PLATFORM_ID;
			}
			set
			{
				if ((this._PLATFORM_ID != value))
				{
					this.OnPLATFORM_IDChanging(value);
					this.SendPropertyChanging();
					this._PLATFORM_ID = value;
					this.SendPropertyChanged("PLATFORM_ID");
					this.OnPLATFORM_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAME", DbType="VarChar(50)")]
		public string NAME
		{
			get
			{
				return this._NAME;
			}
			set
			{
				if ((this._NAME != value))
				{
					this.OnNAMEChanging(value);
					this.SendPropertyChanging();
					this._NAME = value;
					this.SendPropertyChanged("NAME");
					this.OnNAMEChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_M_SERVER")]
	public partial class TBL_M_SERVER : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _SERVER_ID;
		
		private string _NAME;
		
		private string _REMARKS;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSERVER_IDChanging(System.Guid value);
    partial void OnSERVER_IDChanged();
    partial void OnNAMEChanging(string value);
    partial void OnNAMEChanged();
    partial void OnREMARKSChanging(string value);
    partial void OnREMARKSChanged();
    #endregion
		
		public TBL_M_SERVER()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SERVER_ID", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid SERVER_ID
		{
			get
			{
				return this._SERVER_ID;
			}
			set
			{
				if ((this._SERVER_ID != value))
				{
					this.OnSERVER_IDChanging(value);
					this.SendPropertyChanging();
					this._SERVER_ID = value;
					this.SendPropertyChanged("SERVER_ID");
					this.OnSERVER_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAME", DbType="VarChar(50)")]
		public string NAME
		{
			get
			{
				return this._NAME;
			}
			set
			{
				if ((this._NAME != value))
				{
					this.OnNAMEChanging(value);
					this.SendPropertyChanging();
					this._NAME = value;
					this.SendPropertyChanged("NAME");
					this.OnNAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_REMARKS", DbType="VarChar(MAX)")]
		public string REMARKS
		{
			get
			{
				return this._REMARKS;
			}
			set
			{
				if ((this._REMARKS != value))
				{
					this.OnREMARKSChanging(value);
					this.SendPropertyChanging();
					this._REMARKS = value;
					this.SendPropertyChanged("REMARKS");
					this.OnREMARKSChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_M_STATUS")]
	public partial class TBL_M_STATUS : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _STATUS_ID;
		
		private string _NAME;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSTATUS_IDChanging(System.Guid value);
    partial void OnSTATUS_IDChanged();
    partial void OnNAMEChanging(string value);
    partial void OnNAMEChanged();
    #endregion
		
		public TBL_M_STATUS()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STATUS_ID", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid STATUS_ID
		{
			get
			{
				return this._STATUS_ID;
			}
			set
			{
				if ((this._STATUS_ID != value))
				{
					this.OnSTATUS_IDChanging(value);
					this.SendPropertyChanging();
					this._STATUS_ID = value;
					this.SendPropertyChanged("STATUS_ID");
					this.OnSTATUS_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAME", DbType="VarChar(50)")]
		public string NAME
		{
			get
			{
				return this._NAME;
			}
			set
			{
				if ((this._NAME != value))
				{
					this.OnNAMEChanging(value);
					this.SendPropertyChanging();
					this._NAME = value;
					this.SendPropertyChanged("NAME");
					this.OnNAMEChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_T_DB")]
	public partial class TBL_T_DB : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _DB_ID;
		
		private string _NAME;
		
		private string _APP_ID;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnDB_IDChanging(System.Guid value);
    partial void OnDB_IDChanged();
    partial void OnNAMEChanging(string value);
    partial void OnNAMEChanged();
    partial void OnAPP_IDChanging(string value);
    partial void OnAPP_IDChanged();
    #endregion
		
		public TBL_T_DB()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DB_ID", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid DB_ID
		{
			get
			{
				return this._DB_ID;
			}
			set
			{
				if ((this._DB_ID != value))
				{
					this.OnDB_IDChanging(value);
					this.SendPropertyChanging();
					this._DB_ID = value;
					this.SendPropertyChanged("DB_ID");
					this.OnDB_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAME", DbType="VarChar(50)")]
		public string NAME
		{
			get
			{
				return this._NAME;
			}
			set
			{
				if ((this._NAME != value))
				{
					this.OnNAMEChanging(value);
					this.SendPropertyChanging();
					this._NAME = value;
					this.SendPropertyChanged("NAME");
					this.OnNAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_APP_ID", DbType="VarChar(50)")]
		public string APP_ID
		{
			get
			{
				return this._APP_ID;
			}
			set
			{
				if ((this._APP_ID != value))
				{
					this.OnAPP_IDChanging(value);
					this.SendPropertyChanging();
					this._APP_ID = value;
					this.SendPropertyChanged("APP_ID");
					this.OnAPP_IDChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_T_DOC")]
	public partial class TBL_T_DOC : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _DOC_ID;
		
		private string _VERSION;
		
		private System.Nullable<System.DateTime> _RELEASE_DATE;
		
		private string _APP_ID;
		
		private string _DOC_TYPE_ID;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnDOC_IDChanging(System.Guid value);
    partial void OnDOC_IDChanged();
    partial void OnVERSIONChanging(string value);
    partial void OnVERSIONChanged();
    partial void OnRELEASE_DATEChanging(System.Nullable<System.DateTime> value);
    partial void OnRELEASE_DATEChanged();
    partial void OnAPP_IDChanging(string value);
    partial void OnAPP_IDChanged();
    partial void OnDOC_TYPE_IDChanging(string value);
    partial void OnDOC_TYPE_IDChanged();
    #endregion
		
		public TBL_T_DOC()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOC_ID", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid DOC_ID
		{
			get
			{
				return this._DOC_ID;
			}
			set
			{
				if ((this._DOC_ID != value))
				{
					this.OnDOC_IDChanging(value);
					this.SendPropertyChanging();
					this._DOC_ID = value;
					this.SendPropertyChanged("DOC_ID");
					this.OnDOC_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VERSION", DbType="VarChar(50)")]
		public string VERSION
		{
			get
			{
				return this._VERSION;
			}
			set
			{
				if ((this._VERSION != value))
				{
					this.OnVERSIONChanging(value);
					this.SendPropertyChanging();
					this._VERSION = value;
					this.SendPropertyChanged("VERSION");
					this.OnVERSIONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RELEASE_DATE", DbType="Date")]
		public System.Nullable<System.DateTime> RELEASE_DATE
		{
			get
			{
				return this._RELEASE_DATE;
			}
			set
			{
				if ((this._RELEASE_DATE != value))
				{
					this.OnRELEASE_DATEChanging(value);
					this.SendPropertyChanging();
					this._RELEASE_DATE = value;
					this.SendPropertyChanged("RELEASE_DATE");
					this.OnRELEASE_DATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_APP_ID", DbType="VarChar(50)")]
		public string APP_ID
		{
			get
			{
				return this._APP_ID;
			}
			set
			{
				if ((this._APP_ID != value))
				{
					this.OnAPP_IDChanging(value);
					this.SendPropertyChanging();
					this._APP_ID = value;
					this.SendPropertyChanged("APP_ID");
					this.OnAPP_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOC_TYPE_ID", DbType="VarChar(50)")]
		public string DOC_TYPE_ID
		{
			get
			{
				return this._DOC_TYPE_ID;
			}
			set
			{
				if ((this._DOC_TYPE_ID != value))
				{
					this.OnDOC_TYPE_IDChanging(value);
					this.SendPropertyChanging();
					this._DOC_TYPE_ID = value;
					this.SendPropertyChanged("DOC_TYPE_ID");
					this.OnDOC_TYPE_IDChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	public partial class cufn_getAllActivities1Result
	{
		
		private System.Guid _ACTIVITY_ID;
		
		private System.Nullable<System.DateTime> _START_DATETIME;
		
		private System.Nullable<System.DateTime> _END_DATETIME;
		
		private string _ACTIVITY_DETAIL;
		
		private string _REMARKS;
		
		private string _APP_ID;
		
		private string _APP_NAME;
		
		private string _VERSION_ID;
		
		private string _VERSION;
		
		private string _APP_STATUS;
		
		private string _PIC_ID;
		
		private string _PIC_NAME;
		
		private string _STEP_ID;
		
		private string _STEP_NAME;
		
		public cufn_getAllActivities1Result()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ACTIVITY_ID", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid ACTIVITY_ID
		{
			get
			{
				return this._ACTIVITY_ID;
			}
			set
			{
				if ((this._ACTIVITY_ID != value))
				{
					this._ACTIVITY_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_START_DATETIME", DbType="DateTime")]
		public System.Nullable<System.DateTime> START_DATETIME
		{
			get
			{
				return this._START_DATETIME;
			}
			set
			{
				if ((this._START_DATETIME != value))
				{
					this._START_DATETIME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_END_DATETIME", DbType="DateTime")]
		public System.Nullable<System.DateTime> END_DATETIME
		{
			get
			{
				return this._END_DATETIME;
			}
			set
			{
				if ((this._END_DATETIME != value))
				{
					this._END_DATETIME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ACTIVITY_DETAIL", DbType="VarChar(MAX)")]
		public string ACTIVITY_DETAIL
		{
			get
			{
				return this._ACTIVITY_DETAIL;
			}
			set
			{
				if ((this._ACTIVITY_DETAIL != value))
				{
					this._ACTIVITY_DETAIL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_REMARKS", DbType="VarChar(MAX)")]
		public string REMARKS
		{
			get
			{
				return this._REMARKS;
			}
			set
			{
				if ((this._REMARKS != value))
				{
					this._REMARKS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_APP_ID", DbType="VarChar(50)")]
		public string APP_ID
		{
			get
			{
				return this._APP_ID;
			}
			set
			{
				if ((this._APP_ID != value))
				{
					this._APP_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_APP_NAME", DbType="VarChar(200)")]
		public string APP_NAME
		{
			get
			{
				return this._APP_NAME;
			}
			set
			{
				if ((this._APP_NAME != value))
				{
					this._APP_NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VERSION_ID", DbType="VarChar(50)")]
		public string VERSION_ID
		{
			get
			{
				return this._VERSION_ID;
			}
			set
			{
				if ((this._VERSION_ID != value))
				{
					this._VERSION_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VERSION", DbType="VarChar(50)")]
		public string VERSION
		{
			get
			{
				return this._VERSION;
			}
			set
			{
				if ((this._VERSION != value))
				{
					this._VERSION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_APP_STATUS", DbType="VarChar(50)")]
		public string APP_STATUS
		{
			get
			{
				return this._APP_STATUS;
			}
			set
			{
				if ((this._APP_STATUS != value))
				{
					this._APP_STATUS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PIC_ID", DbType="VarChar(50)")]
		public string PIC_ID
		{
			get
			{
				return this._PIC_ID;
			}
			set
			{
				if ((this._PIC_ID != value))
				{
					this._PIC_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PIC_NAME", DbType="VarChar(200)")]
		public string PIC_NAME
		{
			get
			{
				return this._PIC_NAME;
			}
			set
			{
				if ((this._PIC_NAME != value))
				{
					this._PIC_NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STEP_ID", DbType="VarChar(50)")]
		public string STEP_ID
		{
			get
			{
				return this._STEP_ID;
			}
			set
			{
				if ((this._STEP_ID != value))
				{
					this._STEP_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STEP_NAME", DbType="VarChar(200)")]
		public string STEP_NAME
		{
			get
			{
				return this._STEP_NAME;
			}
			set
			{
				if ((this._STEP_NAME != value))
				{
					this._STEP_NAME = value;
				}
			}
		}
	}
	
	public partial class cufn_getAllAppsResult
	{
		
		private System.Guid _APP_ID;
		
		private string _APP_NAME;
		
		private string _OWNER;
		
		private string _PLATFORM_ID;
		
		private string _PLATFORM_NAME;
		
		private string _SERVER_ID;
		
		private string _SERVER_NAME;
		
		private string _STATUS_ID;
		
		private string _STATUS;
		
		public cufn_getAllAppsResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_APP_ID", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid APP_ID
		{
			get
			{
				return this._APP_ID;
			}
			set
			{
				if ((this._APP_ID != value))
				{
					this._APP_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_APP_NAME", DbType="VarChar(200)")]
		public string APP_NAME
		{
			get
			{
				return this._APP_NAME;
			}
			set
			{
				if ((this._APP_NAME != value))
				{
					this._APP_NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OWNER", DbType="VarChar(200)")]
		public string OWNER
		{
			get
			{
				return this._OWNER;
			}
			set
			{
				if ((this._OWNER != value))
				{
					this._OWNER = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PLATFORM_ID", DbType="VarChar(50)")]
		public string PLATFORM_ID
		{
			get
			{
				return this._PLATFORM_ID;
			}
			set
			{
				if ((this._PLATFORM_ID != value))
				{
					this._PLATFORM_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PLATFORM_NAME", DbType="VarChar(50)")]
		public string PLATFORM_NAME
		{
			get
			{
				return this._PLATFORM_NAME;
			}
			set
			{
				if ((this._PLATFORM_NAME != value))
				{
					this._PLATFORM_NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SERVER_ID", DbType="VarChar(50)")]
		public string SERVER_ID
		{
			get
			{
				return this._SERVER_ID;
			}
			set
			{
				if ((this._SERVER_ID != value))
				{
					this._SERVER_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SERVER_NAME", DbType="VarChar(50)")]
		public string SERVER_NAME
		{
			get
			{
				return this._SERVER_NAME;
			}
			set
			{
				if ((this._SERVER_NAME != value))
				{
					this._SERVER_NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STATUS_ID", DbType="VarChar(50)")]
		public string STATUS_ID
		{
			get
			{
				return this._STATUS_ID;
			}
			set
			{
				if ((this._STATUS_ID != value))
				{
					this._STATUS_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STATUS", DbType="VarChar(50)")]
		public string STATUS
		{
			get
			{
				return this._STATUS;
			}
			set
			{
				if ((this._STATUS != value))
				{
					this._STATUS = value;
				}
			}
		}
	}
	
	public partial class cufn_getAllDocsResult
	{
		
		private System.Guid _DOC_ID;
		
		private string _VERSION;
		
		private System.Nullable<System.DateTime> _RELEASE_DATE;
		
		private string _APP_ID;
		
		private string _app_name;
		
		private string _DOC_TYPE_ID;
		
		private string _DOC_TYPE;
		
		public cufn_getAllDocsResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOC_ID", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid DOC_ID
		{
			get
			{
				return this._DOC_ID;
			}
			set
			{
				if ((this._DOC_ID != value))
				{
					this._DOC_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VERSION", DbType="VarChar(50)")]
		public string VERSION
		{
			get
			{
				return this._VERSION;
			}
			set
			{
				if ((this._VERSION != value))
				{
					this._VERSION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RELEASE_DATE", DbType="Date")]
		public System.Nullable<System.DateTime> RELEASE_DATE
		{
			get
			{
				return this._RELEASE_DATE;
			}
			set
			{
				if ((this._RELEASE_DATE != value))
				{
					this._RELEASE_DATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_APP_ID", DbType="VarChar(50)")]
		public string APP_ID
		{
			get
			{
				return this._APP_ID;
			}
			set
			{
				if ((this._APP_ID != value))
				{
					this._APP_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_app_name", DbType="VarChar(200)")]
		public string app_name
		{
			get
			{
				return this._app_name;
			}
			set
			{
				if ((this._app_name != value))
				{
					this._app_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOC_TYPE_ID", DbType="VarChar(50)")]
		public string DOC_TYPE_ID
		{
			get
			{
				return this._DOC_TYPE_ID;
			}
			set
			{
				if ((this._DOC_TYPE_ID != value))
				{
					this._DOC_TYPE_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOC_TYPE", DbType="VarChar(50)")]
		public string DOC_TYPE
		{
			get
			{
				return this._DOC_TYPE;
			}
			set
			{
				if ((this._DOC_TYPE != value))
				{
					this._DOC_TYPE = value;
				}
			}
		}
	}
	
	public partial class cufn_getAllVersionsResult
	{
		
		private System.Guid _VERSION_ID;
		
		private System.Nullable<System.DateTime> _DATE;
		
		private string _VERSION;
		
		private string _APP_ID;
		
		public cufn_getAllVersionsResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VERSION_ID", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid VERSION_ID
		{
			get
			{
				return this._VERSION_ID;
			}
			set
			{
				if ((this._VERSION_ID != value))
				{
					this._VERSION_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DATE", DbType="Date")]
		public System.Nullable<System.DateTime> DATE
		{
			get
			{
				return this._DATE;
			}
			set
			{
				if ((this._DATE != value))
				{
					this._DATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VERSION", DbType="VarChar(50)")]
		public string VERSION
		{
			get
			{
				return this._VERSION;
			}
			set
			{
				if ((this._VERSION != value))
				{
					this._VERSION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_APP_ID", DbType="VarChar(50)")]
		public string APP_ID
		{
			get
			{
				return this._APP_ID;
			}
			set
			{
				if ((this._APP_ID != value))
				{
					this._APP_ID = value;
				}
			}
		}
	}
	
	public partial class cufn_getAllDatabasesResult
	{
		
		private System.Guid _DB_ID;
		
		private string _NAME;
		
		private string _APP_ID;
		
		public cufn_getAllDatabasesResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DB_ID", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid DB_ID
		{
			get
			{
				return this._DB_ID;
			}
			set
			{
				if ((this._DB_ID != value))
				{
					this._DB_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAME", DbType="VarChar(50)")]
		public string NAME
		{
			get
			{
				return this._NAME;
			}
			set
			{
				if ((this._NAME != value))
				{
					this._NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_APP_ID", DbType="VarChar(50)")]
		public string APP_ID
		{
			get
			{
				return this._APP_ID;
			}
			set
			{
				if ((this._APP_ID != value))
				{
					this._APP_ID = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
